// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentalSystem.Infrastructure.Data;

#nullable disable

namespace RentalSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623153433_AddDisplayUserNameToUser")]
    partial class AddDisplayUserNameToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CautionLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PerformedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Route")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Audits", null, t =>
                        {
                            t.HasCheckConstraint("CK_Audit_OldAndNewCantBeSameValue", " \"OldValue\" IS NULL OR \"NewValue\" IS NULL OR \"OldValue\" <> \"NewValue\" ");

                            t.HasCheckConstraint("CK_Audit_PerformedAtCantBeFuture", " \"PerformedAt\" <= CURRENT_TIMESTAMP ");
                        });
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.Damage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)");

                    b.Property<Guid>("EquipmentItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("Fixed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MaintenanceJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RentalOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RentalOrderItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_Damages_EquipmentItemId_CantAddNewWhileOldNotResolved")
                        .HasFilter(" \"Fixed\" = false ");

                    b.HasIndex("MaintenanceJobId")
                        .IsUnique();

                    b.HasIndex("RentalOrderId");

                    b.HasIndex("RentalOrderItemId");

                    b.ToTable("Damages", null, t =>
                        {
                            t.HasCheckConstraint("CK_Damage_FeeCantBeNegative", " \"Fee\" > 0 ");
                        });
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.EquipmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetTagPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTagPrefix")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EquipmentCategories", null, t =>
                        {
                            t.HasCheckConstraint("CK_EquipmentCategory_NormalizedAndOriginalHasSameLength", " LENGTH(\"Name\") = LENGTH(\"NormalizedName\") ");
                        });
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.EquipmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DepositFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("FeePerDay")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<decimal>("LateFeePerDay")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.ToTable("EquipmentItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_EquipmentItems_DepositFeeCantBeNegativeOrZero", "\"DepositFee\" > 0");

                            t.HasCheckConstraint("CK_EquipmentItems_FeePerDayCantBeNegativeOrZero", "\"FeePerDay\" > 0");

                            t.HasCheckConstraint("CK_EquipmentItems_LateFeePerDayCantBeNegativeOrZero", "\"LateFeePerDay\" > 0");
                        });
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DeterminedCondition")
                        .HasColumnType("text");

                    b.Property<DateTime>("InspectionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RentalOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RentalOrderItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("RentalOrderId", "RentalOrderItemId")
                        .IsUnique();

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.MaintenanceJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DamageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MaintenanceStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DamageId")
                        .IsUnique();

                    b.HasIndex("TechnicianId");

                    b.ToTable("MaintenanceJobs");
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RentalOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RentalOrderId");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payment_AmountCantBeNegative", " \"Amount\" >= 0 ");

                            t.HasCheckConstraint("CK_Payment_PaidAtCantBeBeforeCreatedAt", " \"PaidAt\" >= \"CreatedAt\" ");
                        });
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.RentalOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerRequestNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PickUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RentalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("UX_RentalOrders_CustomerId_CanOnlyHasOneUnfinishedOrder")
                        .HasFilter(" \"RentalStatus\" IN ('Pending', 'PickedUp', 'Approved', 'Returned')");

                    b.ToTable("RentalOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_RentalOrder_PickUpAtBeforeReturnedAt", " \"PickUpAt\" IS NULL OR \"ReturnedAt\" IS NULL OR \"PickUpAt\" <= \"ReturnedAt\" ");

                            t.HasCheckConstraint("CK_RentalOrder_StartDateAfterToday", " \"StartDate\" >= CURRENT_DATE ");

                            t.HasCheckConstraint("CK_RentalOrder_StartDateBeforeEndDate", " \"StartDate\" <= \"EndDate\" ");

                            t.HasCheckConstraint("CompletedNeedPickUpAndReturn", " \"RentalStatus\" <> 'Completed' OR (\"PickUpAt\" IS NOT NULL AND \"ReturnedAt\" IS NOT NULL) ");
                        });
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.RentalOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DepositFeeAtRental")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("EquipmentItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FeePerDayAtRental")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LateFeePerDayAtRental")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RentalOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId")
                        .IsUnique();

                    b.HasIndex("RentalOrderId");

                    b.HasIndex("EquipmentItemId", "RentalOrderId")
                        .IsUnique();

                    b.ToTable("RentalOrderItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_RentalOrderItems_DepositFeeAtRentalCantBeNegativeOrZero", "\"DepositFeeAtRental\" > 0");

                            t.HasCheckConstraint("CK_RentalOrderItems_FeePerDayAtRentalCantBeNegativeOrZero", "\"FeePerDayAtRental\" > 0");

                            t.HasCheckConstraint("CK_RentalOrderItems_LateFeePerDayAtRentalCantBeNegativeOrZero", "\"LateFeePerDayAtRental\" > 0");
                        });
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.RentalStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldStatus")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RentalOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("RentalOrderId");

                    b.ToTable("RentalStatusHistories", null, t =>
                        {
                            t.HasCheckConstraint("CK_RentalOrderHistory_OldAndNewValueCantBeSame", " \"OldStatus\" IS NULL OR \"OldStatus\" <> \"NewStatus\" ");
                        });
                });

            modelBuilder.Entity("RentalSystem.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("EmployeeStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RentalSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RentalSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RentalSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.Damage", b =>
                {
                    b.HasOne("RentalSystem.Domain.Entities.EquipmentItem", "EquipmentItem")
                        .WithMany()
                        .HasForeignKey("EquipmentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalSystem.Domain.Entities.RentalOrder", "RentalOrder")
                        .WithMany("Damages")
                        .HasForeignKey("RentalOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalSystem.Domain.Entities.RentalOrderItem", "RentalOrderItem")
                        .WithMany()
                        .HasForeignKey("RentalOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentItem");

                    b.Navigation("RentalOrder");

                    b.Navigation("RentalOrderItem");
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.EquipmentCategory", b =>
                {
                    b.HasOne("RentalSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.EquipmentItem", b =>
                {
                    b.HasOne("RentalSystem.Domain.Entities.EquipmentCategory", "EquipmentCategory")
                        .WithMany("EquipmentItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentCategory");
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.Inspection", b =>
                {
                    b.HasOne("RentalSystem.Domain.Entities.RentalOrder", "RentalOrder")
                        .WithMany()
                        .HasForeignKey("RentalOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RentalOrder");
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.MaintenanceJob", b =>
                {
                    b.HasOne("RentalSystem.Domain.Entities.Damage", "Damage")
                        .WithOne("MaintenanceJob")
                        .HasForeignKey("RentalSystem.Domain.Entities.MaintenanceJob", "DamageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Damage");
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.Payment", b =>
                {
                    b.HasOne("RentalSystem.Domain.Entities.RentalOrder", "RentalOrder")
                        .WithMany("Payments")
                        .HasForeignKey("RentalOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RentalOrder");
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.RentalOrder", b =>
                {
                    b.HasOne("RentalSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.RentalOrderItem", b =>
                {
                    b.HasOne("RentalSystem.Domain.Entities.EquipmentItem", "EquipmentItem")
                        .WithMany()
                        .HasForeignKey("EquipmentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalSystem.Domain.Entities.Inspection", "Inspection")
                        .WithOne("RentalOrderItem")
                        .HasForeignKey("RentalSystem.Domain.Entities.RentalOrderItem", "InspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalSystem.Domain.Entities.RentalOrder", "RentalOrder")
                        .WithMany("Items")
                        .HasForeignKey("RentalOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentItem");

                    b.Navigation("Inspection");

                    b.Navigation("RentalOrder");
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.RentalStatusHistory", b =>
                {
                    b.HasOne("RentalSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RentalSystem.Domain.Entities.RentalOrder", "RentalOrder")
                        .WithMany("RentalStatusHistories")
                        .HasForeignKey("RentalOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RentalOrder");
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.Damage", b =>
                {
                    b.Navigation("MaintenanceJob")
                        .IsRequired();
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.EquipmentCategory", b =>
                {
                    b.Navigation("EquipmentItems");
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.Inspection", b =>
                {
                    b.Navigation("RentalOrderItem")
                        .IsRequired();
                });

            modelBuilder.Entity("RentalSystem.Domain.Entities.RentalOrder", b =>
                {
                    b.Navigation("Damages");

                    b.Navigation("Items");

                    b.Navigation("Payments");

                    b.Navigation("RentalStatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
